#!/usr/bin/env python3
"""
Emit a shell script that performs HTTP contrib downloads for the current freeunit tree.

URLs are taken from pkg/contrib/src/*/Makefile (first argument to download_pkg, e.g.
WASI_SYSROOT_URL, NJS_URL) after expanding version variables — same strings as upstream,
no packages.freeunit.org mirror and no fallback URLs.

Git-based contrib (e.g. libunit-wasm) is left to `make -C pkg/contrib fetch` when enabled.

Contrib slugs skipped here (see patch_upstream.py): wasi-sysroot (and libunit-wasm).
"""
from __future__ import annotations

import argparse

# pkg/contrib/src/<slug>/ — omitted from HTTP prefetch (COPR temporary)
SKIP_CONTRIB_SLUGS = frozenset({"wasi-sysroot"})
import os
import re
import sys
from pathlib import Path


def strip_make_comment(line: str) -> str:
    i = line.find("#")
    if i == -1:
        return line.rstrip()
    return line[:i].rstrip()


def parse_assignments(text: str) -> dict[str, str]:
    """Parse top-level VAR := / ?= / = lines (no targets)."""
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = strip_make_comment(raw)
        if not line or line.startswith("\t"):
            continue
        if ":" in line and not re.match(r"^\s*\w+\s*[?:]?=", line):
            # likely a target line
            continue
        m = re.match(r"^(\w+)\s*(?::=|\?=|=)\s*(.*)$", line)
        if not m:
            continue
        out[m.group(1)] = m.group(2).strip()
    return out


def expand_vars(expr: str, env: dict[str, str], *, where: str) -> str:
    for _ in range(256):
        m = re.search(r"\$\((\w+)\)", expr)
        if not m:
            return expr
        name = m.group(1)
        if name not in env:
            sys.exit(f"{where}: undefined make variable $({name}) in {expr!r}")
        expr = expr[: m.start()] + env[name] + expr[m.end() :]
    sys.exit(f"{where}: recursive or too-deep variable expansion in {expr!r}")


def load_version_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    return parse_assignments(path.read_text(encoding="utf-8"))


# Target + single-line download_pkg recipe (upstream pkg/contrib pattern).
DOWNLOAD_PKG_RULE = re.compile(
    r"^\$\(TARBALLS\)/(.+?)\s*:\s*\n\t[ \t]*\$\(call download_pkg,\s*([^,]+),\s*([^)]+)\)\s*$",
    re.MULTILINE,
)


def _expand_download_url(url_arg: str, env: dict[str, str], mk: Path) -> str:
    url_arg = url_arg.strip()
    if url_arg.startswith("$(") and url_arg.endswith(")"):
        ukey = url_arg[2:-1]
        if ukey not in env:
            sys.exit(f"{mk}: unknown URL variable {url_arg}")
        raw = env[ukey]
    else:
        raw = url_arg
    return expand_vars(raw, env, where=f"{mk}:download_pkg url")


def discover_http_fetches(worktree: Path) -> list[tuple[str, str]]:
    """Return list of (tarball_basename, url) from upstream download_pkg primary URL."""
    contrib = worktree / "pkg" / "contrib"
    src = contrib / "src"
    if not src.is_dir():
        sys.exit(f"missing {src}")

    items: list[tuple[str, str]] = []

    for mk in sorted(src.glob("*/Makefile")):
        if mk.parent.name in SKIP_CONTRIB_SLUGS:
            continue
        body = mk.read_text(encoding="utf-8")
        env: dict[str, str] = {}
        env.update(load_version_file(mk.parent / "version"))
        for raw in body.splitlines():
            line = strip_make_comment(raw)
            if not line or line.startswith("\t"):
                continue
            if ":" in line and not re.match(r"^\s*\w+\s*[?:]?=", line):
                continue
            m = re.match(r"^(\w+)\s*(?::=|\?=|=)\s*(.*)$", line)
            if not m:
                continue
            key, rhs = m.group(1), m.group(2).strip()
            env[key] = expand_vars(rhs, env, where=f"{mk}:{key}")

        for tmatch in DOWNLOAD_PKG_RULE.finditer(body):
            target_pat, url_arg, _pkg_slug = tmatch.groups()
            fname = expand_vars(target_pat.strip(), env, where=f"{mk}:target")
            base = os.path.basename(fname)
            url = _expand_download_url(url_arg, env, mk)
            items.append((base, url))

    return items


def emit_shell(items: list[tuple[str, str]]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by freeunit-copr/.copr/gen_contrib_fetch.py — do not edit.",
        "# HTTP fetch: one curl per tarball; URL from upstream pkg/contrib/src/*/Makefile (*_URL).",
        "set -euo pipefail",
        f'WORKTREE="${{1:?"usage: $0 /path/to/freeunit-checkout"}}"',
        'case "$WORKTREE" in /*) ;; *) WORKTREE="$(pwd)/$WORKTREE" ;; esac',
        'T="$WORKTREE/pkg/contrib/tarballs"',
        'mkdir -p "$T"',
        "",
    ]
    for base, url in items:
        lines.append(f'echo "contrib fetch: {base} <= {url}"')
        lines.append(
            f'curl -fL --retry 3 --retry-delay 5 -o "$T/{base}" "{url}"'
        )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--worktree", type=Path, required=True)
    ap.add_argument("--out", type=Path, help="Write generated shell here")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Parse only; print basename and URL from upstream Makefile",
    )
    args = ap.parse_args()
    worktree = args.worktree.resolve()
    items = discover_http_fetches(worktree)
    if not items:
        sys.exit("gen_contrib_fetch: no $(call download_pkg,...) rules found")
    if args.check:
        for base, url in items:
            print(base, url, sep="\t")
        return
    script = emit_shell(items)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(script, encoding="utf-8")
        os.chmod(args.out, 0o755)
    else:
        sys.stdout.write(script)


if __name__ == "__main__":
    main()
