#!/usr/bin/env python3
"""
Emit a shell script that performs HTTP contrib downloads for the current freeunit tree.

URLs, mirror order, and tarball names are derived from pkg/contrib/Makefile and
pkg/contrib/src/*/Makefile (same semantics as $(call download_pkg,...)). No hardcoded
package list — add a new download_pkg-based tarball upstream and this picks it up.

Git-based contrib (e.g. libunit-wasm) is left to `make -C pkg/contrib fetch`.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


def strip_make_comment(line: str) -> str:
    i = line.find("#")
    if i == -1:
        return line.rstrip()
    return line[:i].rstrip()


def parse_assignments(text: str) -> dict[str, str]:
    """Parse top-level VAR := / ?= / = lines (no targets)."""
    out: dict[str, str] = {}
    for raw in text.splitlines():
        line = strip_make_comment(raw)
        if not line or line.startswith("\t"):
            continue
        if ":" in line and not re.match(r"^\s*\w+\s*[?:]?=", line):
            # likely a target line
            continue
        m = re.match(r"^(\w+)\s*(?::=|\?=|=)\s*(.*)$", line)
        if not m:
            continue
        out[m.group(1)] = m.group(2).strip()
    return out


def expand_vars(expr: str, env: dict[str, str], *, where: str) -> str:
    for _ in range(256):
        m = re.search(r"\$\((\w+)\)", expr)
        if not m:
            return expr
        name = m.group(1)
        if name not in env:
            sys.exit(f"{where}: undefined make variable $({name}) in {expr!r}")
        expr = expr[: m.start()] + env[name] + expr[m.end() :]
    sys.exit(f"{where}: recursive or too-deep variable expansion in {expr!r}")


def load_version_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    return parse_assignments(path.read_text(encoding="utf-8"))


def parse_contrib_freeunit(contrib_mf: Path) -> str:
    text = contrib_mf.read_text(encoding="utf-8")
    env = parse_assignments(text)
    base = env.get("CONTRIB_FREEUNIT", "https://packages.freeunit.org")
    return expand_vars(base, env, where=str(contrib_mf))


# Target + single-line download_pkg recipe (upstream pkg/contrib pattern).
DOWNLOAD_PKG_RULE = re.compile(
    r"^\$\(TARBALLS\)/(.+?)\s*:\s*\n\t[ \t]*\$\(call download_pkg,\s*([^,]+),\s*([^)]+)\)\s*$",
    re.MULTILINE,
)


def discover_http_fetches(worktree: Path) -> list[tuple[str, str, str]]:
    """
    Return list of (tarball_basename, primary_url, pkg_folder_for_mirror)
    mirroring download_pkg order: CONTRIB_FREEUNIT/<pkg>/<file> then primary URL.
    """
    contrib = worktree / "pkg" / "contrib"
    contrib_mf = contrib / "Makefile"
    if not contrib_mf.is_file():
        sys.exit(f"missing {contrib_mf}")

    cdn = parse_contrib_freeunit(contrib_mf)
    items: list[tuple[str, str, str]] = []

    src = contrib / "src"
    if not src.is_dir():
        sys.exit(f"missing {src}")

    for mk in sorted(src.glob("*/Makefile")):
        pkg = mk.parent.name
        body = mk.read_text(encoding="utf-8")
        env: dict[str, str] = {}
        env.update(load_version_file(mk.parent / "version"))
        # Apply package Makefile assignments in source order.
        for raw in body.splitlines():
            line = strip_make_comment(raw)
            if not line or line.startswith("\t"):
                continue
            if ":" in line and not re.match(r"^\s*\w+\s*[?:]?=", line):
                continue
            m = re.match(r"^(\w+)\s*(?::=|\?=|=)\s*(.*)$", line)
            if not m:
                continue
            key, rhs = m.group(1), m.group(2).strip()
            env[key] = expand_vars(rhs, env, where=f"{mk}:{key}")

        for tmatch in DOWNLOAD_PKG_RULE.finditer(body):
            target_pat, url_arg, pkg_slug = tmatch.groups()
            url_arg = url_arg.strip()
            pkg_slug = pkg_slug.strip()
            fname = expand_vars(target_pat.strip(), env, where=f"{mk}:target")
            if url_arg.startswith("$(") and url_arg.endswith(")"):
                ukey = url_arg[2:-1]
                if ukey not in env:
                    sys.exit(f"{mk}: unknown URL variable {url_arg}")
                primary = expand_vars(env[ukey], env, where=f"{mk}:{ukey}")
            else:
                primary = expand_vars(url_arg, env, where=f"{mk}:url")
            base = os.path.basename(fname)
            mirror = f"{cdn.rstrip('/')}/{pkg_slug}/{base}"
            items.append((base, primary, mirror))

    return items


def emit_shell(worktree: Path, items: list[tuple[str, str, str]]) -> str:
    wt = str(worktree.resolve())
    lines = [
        "#!/usr/bin/env bash",
        "# Generated by freeunit-copr/.copr/gen_contrib_fetch.py — do not edit.",
        "# Curl invocations derived from upstream pkg/contrib Makefiles at SRPM time.",
        "set -euo pipefail",
        f'WORKTREE="${{1:?"usage: $0 /path/to/freeunit-checkout"}}"',
        f'case "$WORKTREE" in /*) ;; *) WORKTREE="$(pwd)/$WORKTREE" ;; esac',
        'T="$WORKTREE/pkg/contrib/tarballs"',
        'mkdir -p "$T"',
        "try() {",
        "  local out=$1; shift",
        "  local u",
        '  for u in "$@"; do',
        "    if curl -fL --retry 3 --retry-delay 5 -o \"$out\" \"$u\"; then",
        "      return 0",
        "    fi",
        "  done",
        "  return 1",
        "}",
        "",
    ]
    for base, primary, mirror in items:
        lines.append(f'echo "contrib fetch: {base}"')
        lines.append(f'try "$T/{base}" \\')
        lines.append(f'  "{mirror}" \\')
        lines.append(f'  "{primary}"')
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--worktree", type=Path, required=True)
    ap.add_argument("--out", type=Path, help="Write generated shell here")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Parse only; print discovered tarballs (no script output)",
    )
    args = ap.parse_args()
    worktree = args.worktree.resolve()
    items = discover_http_fetches(worktree)
    if not items:
        sys.exit("gen_contrib_fetch: no $(call download_pkg,...) rules found")
    if args.check:
        for base, primary, mirror in items:
            print(base, mirror, primary, sep="\t")
        return
    script = emit_shell(worktree, items)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(script, encoding="utf-8")
        os.chmod(args.out, 0o755)
    else:
        sys.stdout.write(script)


if __name__ == "__main__":
    main()
